config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  root 'welcome#index'

  resources :characters

end

app/models/character.rb
class Character < ActiveRecord::Base
  validates :name, presence: true, length:{minimum: 1}
  validates :nickname, presence: true, length:{minimum: 1}
  validates :superpower, presence: true, length:{minimum: 1}
end

app/models/high_score.rb
class HighScore < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  def index
    @characters = Character.all
  end

  def new
    @character = Character.new
  end

  def create
    @character = Character.new(character_params)

    if @character.save
      redirect_to @character
    else
      render 'new'
    end
  end

  def show
    @character = Character.find(params[:id])
  end

  def edit
    @character = Character.find(params[:id])
  end

  def update
    @character = Character.find(params[:id])
    if @character.update(character_params)
      redirect_to @character
    else
      render 'edit'
    end
  end

  def destroy
    @character = Character.find(params[:id])
    @character.destroy

    redirect_to characters_path
  end

  private
  def character_params
    params.require(:character).permit(:name, :nickname, :superpower)
  end
end

app/controllers/greetings_controller.rb
class GreetingsController < ApplicationController
  def hello
    @message = "Hello World"
  end
end

app/controllers/high_scores_controller.rb
class HighScoresController < ApplicationController
  before_action :set_high_score, only: [:show, :edit, :update, :destroy]

  # GET /high_scores
  # GET /high_scores.json
  def index
    @high_scores = HighScore.all
  end

  # GET /high_scores/1
  # GET /high_scores/1.json
  def show
  end

  # GET /high_scores/new
  def new
    @high_score = HighScore.new
  end

  # GET /high_scores/1/edit
  def edit
  end

  # POST /high_scores
  # POST /high_scores.json
  def create
    @high_score = HighScore.new(high_score_params)

    respond_to do |format|
      if @high_score.save
        format.html { redirect_to @high_score, notice: 'High score was successfully created.' }
        format.json { render :show, status: :created, location: @high_score }
      else
        format.html { render :new }
        format.json { render json: @high_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /high_scores/1
  # PATCH/PUT /high_scores/1.json
  def update
    respond_to do |format|
      if @high_score.update(high_score_params)
        format.html { redirect_to @high_score, notice: 'High score was successfully updated.' }
        format.json { render :show, status: :ok, location: @high_score }
      else
        format.html { render :edit }
        format.json { render json: @high_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /high_scores/1
  # DELETE /high_scores/1.json
  def destroy
    @high_score.destroy
    respond_to do |format|
      format.html { redirect_to high_scores_url, notice: 'High score was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_high_score
      @high_score = HighScore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def high_score_params
      params.require(:high_score).permit(:game, :score)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/character_helper.rb
module CharacterHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/greetings_helper.rb
module GreetingsHelper
end

app/helpers/high_scores_helper.rb
module HighScoresHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/characters/_form.html.erb
<%= form_for @character do |f| %>
  <% if @character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@character.errors.count, "error") %> prohibited
        this article from being saved:</h2>
      <ul>
      <% @character.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :nickname %><br>
    <%= f.text_field :nickname %>
  </p>
  <p>
    <%= f.label :superpower %><br/>
    <%= f.text_field :superpower %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing character</h1>
<%= render 'form' %>
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<h1>Listing characters</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>Superpower</th>
    <th colspan="3"></th>
  </tr>

  <% @characters.each do |character| %>
    <tr>
      <td><%= character.name %></td>
      <td><%= character.nickname %></td>
      <td><%= character.superpower %></td>
      <td><%= link_to 'Show', character_path(character) %></td>
      <td><%= link_to 'Edit', edit_character_path(character) %></td>
      <td><%= link_to 'Delete', character_path(character), method: :delete, data:{confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>


<p><%= link_to 'Create New Character', new_character_path %></p>
<p><%= link_to 'Back', root_path %></p>

app/views/characters/new.html.erb
<h1>New Character</h1>
<%= render 'form' %>
<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @character.name %>
</p>

<p>
  <strong>Text:</strong>
  <%= @character.nickname %>
</p>

<p>
  <strong>Text:</strong>
  <%= @character.superpower %>
</p>

<%= link_to 'All Characters', characters_path %> | <%= link_to 'Edit', edit_character_path(@character) %>

app/views/greetings/hello.html.erb
<h1>Greetings#hello</h1>
<p><%= @message %></p>

app/views/high_scores/_form.html.erb
<%= form_for(@high_score) do |f| %>
  <% if @high_score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@high_score.errors.count, "error") %> prohibited this high_score from being saved:</h2>

      <ul>
      <% @high_score.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :game %><br>
    <%= f.text_field :game %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/high_scores/edit.html.erb
<h1>Editing high_score</h1>

<%= render 'form' %>

<%= link_to 'Show', @high_score %> |
<%= link_to 'Back', high_scores_path %>

app/views/high_scores/index.html.erb
<h1>Listing high_scores</h1>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @high_scores.each do |high_score| %>
      <tr>
        <td><%= high_score.game %></td>
        <td><%= high_score.score %></td>
        <td><%= link_to 'Show', high_score %></td>
        <td><%= link_to 'Edit', edit_high_score_path(high_score) %></td>
        <td><%= link_to 'Destroy', high_score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New High score', new_high_score_path %>

app/views/high_scores/new.html.erb
<h1>New high_score</h1>

<%= render 'form' %>

<%= link_to 'Back', high_scores_path %>

app/views/high_scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game:</strong>
  <%= @high_score.game %>
</p>

<p>
  <strong>Score:</strong>
  <%= @high_score.score %>
</p>

<%= link_to 'Edit', edit_high_score_path(@high_score) %> |
<%= link_to 'Back', high_scores_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Playground</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to the playground</h1>
<%= link_to 'All Characters', controller: 'characters' %>
<%= link_to 'Create a new character', new_character_path %>